### ISSUE TITLE
Upgrade PGX Adapter to latest version

### ISSUE THREAD

**Issue by douglaszuqueto** [VinGarcia/ksql#33]
Upgrade PGX Adapter to latest version - PGX v5

Reference: https://github.com/jackc/pgx

**Comment by VinGarcia** [comment]
Hye @douglaszuqueto,

Thanks for submitting this issue, I will try to do it this weekend =]

**Comment by VinGarcia** [comment]
Done on PR #36 instead of updating to the latest version we created a new adapter on `github.com/vingarcia/ksql/adapters/kpgx5`.

Since this was a breaking change from pgx v4 to pgx v5 I think we should keep two separate adapters instead.

Finally I am not sure how stable pgx5 is right now, so we should use it experimentally, I scrolled through the issues session and it looks like we have a significant number of new issues regarding v5.

That said I am closing this issue as this new adapter should do it.
