### ISSUE TITLE
kpgx adapters shouldn't import github.com/lib/pq

### ISSUE THREAD

**Issue by eikemeier** [VinGarcia/ksql#41]
The idea of using github.com/jackc/pgx is to not use github.com/lib/pq…

**Comment by VinGarcia** [comment]
Oh, you are right, sorry, I must have kept it there ever since I didn't have support for pgx. I am on it.

**Comment by VinGarcia** [comment]
Uhm, ok I was using that on the tests. This will take a little longer to fix because I was creating the test tables using `database/sql`. I will work on it throughout this week.

Thanks for noticing it! =]

**Comment by VinGarcia** [comment]
So for now I think there is nothing more we can do about it. I was able to make it vanish from `kpgx/go.mod` which is something, and I removed it from the tests, so now our tests are better decoupled from the adapters which is also something good for the future.

For some reason it did not go away from the `kpgx5/go.mod` file, I am not sure what to do about that. It is apparently a dependency of the dockertest project, but the `kpgx/` package is also using it, so maybe there is more to it, but I don't think this is a big issue since it should not be present on the final compiled binary.

I will close this issue, feel free to open a new one if you think there is more to be done here, or on any other area of the project. And again thanks for reporting this issue, I was indeed importing it explicitly before which would make it show up on the binary.
