### ISSUE TITLE
Common Fields in Model

### ISSUE THREAD

**Issue by n-keist** [VinGarcia/ksql#48]
Hi there, great library to begin with!

I'd like to suggest a feature: 
Allow embedding a BaseModel e.g:

```go
type BaseModel struct {
  ID uuid.UUID `ksql:"id" json:"-"`
  CreatedAt time.Time `ksql:"created_at,timeNowUTC" json:"createdAt"`
}
```

```go
type User struct {
  BaseModel
  Email string `ksql:"email" json:"email"`
  AnotherField string `ksql:"something"`
  ...
}
```

Thanks!

**Comment by VinGarcia** [comment]
Hey @n-keist I am thinking about it, and adding this feature is somewhat of a dilema for me, because I want to keep things as simple as possible, and only add complexity where it is extremely useful. 

This adds two sources of complexity:

1. People will need to understand how KSQL interpreted embedded structs
2. Having a BaseModel as you showed would make the list of values on the struct less explicit

That said this is something that the JSON library also does, which might mean people would be used to this behavior.

I leaning towards not adding it or putting it at the end of the backlog.

I can imagine that the main use-case for this is not having to type down these two fields `ID` and `CreatedAt` more times than necessary, which is not nothing but might not be "extremely useful", but maybe you have some example of use-cases where this feature would be particularly important/useful.

**Comment by n-keist** [comment]
Another use case would be Postgres inheritance, you could easily create parent-child structs that resemble a table. 

But keeping the library as simple as possible is a fair point :D

Thanks!

**Comment by VinGarcia** [comment]
I will keep it int mind, if we can think of more situations I will consider adding it.

Feel free to reopen this ticket or create a new one if you have any new ideas.

I will close this one for now.
