### ISSUE TITLE
Support for slices in SELECT generation with JOINs

### ISSUE THREAD

**Issue by giovanni-orciuolo** [VinGarcia/ksql#50]
Currently, the [wiki article](https://github.com/VinGarcia/ksql/wiki/Reusing-Existing-Structs-on-Queries-with-JOINs) shows this example:

```golang
var row struct{
	User User `tablename:"u"`     // (here the tablename must match the aliased tablename in the query)
	Post Post `tablename:"posts"` // (if no alias is used you should use the actual name of the table)
}
err = db.QueryOne(ctx, &row, "FROM users as u JOIN posts ON u.id = posts.user_id WHERE u.id = ?", userID)
if err != nil {
	panic(err.Error())
}
```

However, this assumes that a given User has a single Post. Obviously this is not always true, so I tried to modify it like this to obtain the list of Posts:

```golang
var row struct{
	User User `tablename:"u"`     // (here the tablename must match the aliased tablename in the query)
	Post []Post `tablename:"posts"` // (if no alias is used you should use the actual name of the table)
}
err = db.QueryOne(ctx, &row, "FROM users as u JOIN posts ON u.id = posts.user_id WHERE u.id = ?", userID)
if err != nil {
	panic(err.Error())
}
```

Unfortunately I get the following error:
`expected nested struct with tablename:"posts" to be a kind of Struct, but got []Post`

Apparently there is no support for this feature. Is this done on purpose? Am I doing this wrong? If so, how can I retrieve the list of Posts?

**Comment by VinGarcia** [comment]
Hey @giovanni-orciuolo, sorry I only saw your message now.

Yes this is not possible because of how SQL works:

KSQL does not alter the query you wrote except for adding the right names to the "SELECT" part of the statement. So what we actually get back from the database is a single table, in the case of the query you shared each row of this table contains the same user duplicated + the post associated with it, for example this could look like this:

| u.id | u.name | u.email | post.id | post.user_id | post.title | post.msg |
|----|----|----|----|----|----|----|
| 42 | 'Iara' | 'iara@gmail.com' | 1 | 42 | 'Post 1' | 'some msg' |
| 42 | 'Iara' | 'iara@gmail.com' | 2 | 42 | 'Post 2' | 'some msg' |
| 42 | 'Iara' | 'iara@gmail.com' | 3 | 42 | 'Post 3' | 'some msg' |
| 42 | 'Iara' | 'iara@gmail.com' | 4 | 42 | 'Post 4' | 'some msg' |
| 42 | 'Iara' | 'iara@gmail.com' | 5 | 42 | 'Post 5' | 'some msg' |
| 42 | 'Iara' | 'iara@gmail.com' | 6 | 42 | 'Post 6' | 'some msg' |
| 42 | 'Iara' | 'iara@gmail.com' | 7 | 42 | 'Post 7' | 'some msg' |

So then comes the question: How to convert this to the struct you shared (and yes I have thought about implementing this feature at some point):

We could just read the data for the first row of the user and ignore the user section of every other row, but this one important problem:

We are loading all the fields for the user table N times and ignoring it N-1 times, so if this table is big this might mean that KSQL would be hiding from the user a very big load of data that would be transferred through the wire unnecessarily. Also if we support this for multiple JOINs this probably would grow exponentially as each new JOIN can bring N times more duplicated rows.

And one of the premises of KSQL is that it should make it harder for the user to make mistakes, and this would be a impactful performance mistake.

-----

A possible alternative would be for KSQL to change the query you actually wrote and instead create several queries, one for posts, one for the user, and one more for each slice of attributes you have on your struct.

This could potentially work, but it would still hide a lot from the user, for example maybe it is a slow query, and if we executed it only once that would be fine but if KSQL decides to run it once per attribute selecting just what we need on each step this could become an extremely slow query.

Anything more advanced than this would require us to parse the SQL which would be beyond what KSQL proposes.

So the right solution for this would probably be to do two queries instead of one, first you get the user using `QueryOne()` then you get the posts using `Query()`.

**Comment by giovanni-orciuolo** [comment]
Thank you for the information. I now realize that what I am asking for is essentially a feature you could find in an ORM, not a query builder. You are right on the performance implications of such feature, even though it is unfortunate that I can't perform JOINs and automatically populate slices with them. You can close the issue if you want, or if other people would like this feature we can further discuss potential implementations.

**Comment by VinGarcia** [comment]
Yeah, I feel the same it would be very convenient to have this feature, but its probably more than what KSQL proposes.

That said, you might be able to get away with something like this:

```go
var user User
err = errors.Join(
    db.QueryOne(ctx, &user, "FROM users WHERE u.id = ?", userID),
    db.Query(ctx, &user.Posts, "FROM posts WHERE user_id = ?", userID),
)
if err != nil {
	panic(err.Error())
}
```

Which is also a pretty clean solution (assuming your User struct has a Posts attribute).

That said I will close this issue then, feel free to reopen this one or create a new one at any time =]

**Comment by VinGarcia** [comment]
Hmm, thinking better of it, I don't think this is good or generic enough to be worth adding to the docs, I will just close the issue for now. Again feel free to open a new one or comment on this one if you have any other issue.

**Comment by bitbandit01** [comment]
Hi Vin,
just a quick note, I think the example you provided above actually would be useful in the wiki.  While taking a look at using ksql for a project the lingering question I had was about how it is designed to handle one-to-many joins.  I couldnt find this in the wiki or in your examples folder but this post has now clarified it for me, so it would probably also be useful to others.

**Comment by VinGarcia** [comment]
Thanks @bitbandit01, I will add it soon then =]

**Comment by VinGarcia** [comment]
Hey @bitbandit01, I just added some more examples to the README:

https://github.com/vingarcia/ksql?tab=readme-ov-file#lets-start-with-some-code

This should give a more comprehensive view of what KSQL is capable of right at the beginning, I imagine this might help beginners get a more complete understanding of the tool sooner.
